oracc/nisaba

python/README.md
python/generate_syntax_highlightining.py
python/requirements.txt
syntaxes/atf.tmLanguage.json

NOTE: at this moment, this is only a proof-of-concept, but it will serve as
basis for generating the syntax with PyOracc

Add script to programmatically generate syntax

---

.gitignore
package-lock.json
package.json
src/test/runTest.ts
src/test/suite/example.atf
src/test/suite/grammar.test.ts
src/test/suite/index.ts

This is incomplete as it isn't testing anything at the moment, but it loads the
grammar and applies tokenization correctly on a sample file.  We only need to
test that the tokenization works as expected.

Add basic testing for grammar

---

package-lock.json
package.json
src/extension.ts
src/logger.ts
src/test/suite/grammar.test.ts
src/test/suite/logger.test.ts

Address #26 and #33.  Alternative to #27: we use Winston directly so we have
full control of the logging format.

Use Winston for logging

---

src/extension.ts
src/preview.ts

- Live updates
- Open preview in separate column
These are quite rough and there are some doubts about how best to dispose of things, so if someone understands the lifecycle of extensions better, comments are welcome :)

Enhance arabic preview

---

LICENSE.txt

This is the same license as Nammu (I copied the file).  Fixes #58.

Add GPL 3 license file

---

src/client/server_result.ts
src/test/suite/reference/user_log_error.log
src/test/suite/validation.test.ts

Show full error message

---

src/atf_model.ts
src/extension.ts
src/test/suite/atf.test.ts
src/test/suite/input/AD6_164.atf
src/test/suite/input/no_project.atf
src/test/suite/input/two_projects.atf

Get project code from ATF

---

.github/ISSUE_TEMPLATE/I_need_help.md
.github/ISSUE_TEMPLATE/feature_request.md

Added issue templates to report problems and ask for new features.

---

src/client/SOAP_client.ts

Don't show low-level validation/lemmatisation log to the user

---

src/client/SOAP_client.ts
src/test/suite/validation.test.ts

Add test for validation of filenames with spaces

---

atf-language-configuration.json
glo-language-configuration.json
package.json
python/README.md
python/generate_syntax_highlightining.py
src/test/suite/grammar.test.ts
src/test/suite/input/grammar_example.glo
syntaxes/glo.tmLanguage.json

Very WIP at the moment, to get this started

Add basic syntax highlighting for glossary files

---

src/client/SOAP_client.ts

- More detailed logging (fixes #111)
- More generous waiting time (related to #110)

Improvements for server communication

---

CHANGELOG.md
package.json
src/extension.ts
src/glo_outline.ts
src/test/suite/glo_outline.test.ts
src/test/suite/grammar.test.ts
src/test/suite/input/grammar_example.glo

Show outline of letters and entries in glossary files

---

CHANGELOG.md
src/atf_model.ts
src/test/suite/atf.test.ts
src/test/suite/input/na-archival.atf
src/test/suite/input/two_projects.atf

Fixes #117.
Will need a changelog entry but waiting for #116 to update that first.

Allow multiple texts from same project in one file

---

docs/about.md
docs/development.md
docs/remote-files.md
docs/user_guide.md
docs/working-with-glo-files.md

Still work in progress (I want to add a short video to showcase navigating glossaries), but saving the progress so far.
Fix #120.

Add documentation for glossaries and remote files

---

.github/ISSUE_TEMPLATE/I_need_help.md

Prompted by #129, it's generally useful to also know what version of Nisaba they're using.

Ask for Nisaba version in bug template

---

CHANGELOG.md

[ChangeLog] Mention fix to lemmatisation/validation on Windows

---

package-lock.json
package.json

Require `Remote - SSH` extension as dependency

---

README.md

This also caused the new release to be rejected by the Marketplace.

Remove non-working badge from README

---

docs/development.md
docs/installation.md
docs/remote-files.md

* Add more details about the publishing process
* Minor adjustments to the installation instructions
* Slightly clearer information about editing remote files and installation of
Nisaba on remote server

Update some docs

---

src/test/suite/input/belsunu.atf
src/test/suite/input/error_belsunu.atf

Validation has been improved server-side and is now flagging some errors that
were not previously reported, but this made our "clean" file fail validation.

Update test input files to make validation pass correctly

---

docs/development.md

Like #138, post-release PR to provide more information about how things work.

[docs] Add more information about the tokens for publishing a release
