src/logger.ts

During today pair programming I realised that we need to call this function to
actually show the output channel, if not visible already.

Show output channel before sending logging messages

---

src/server/messages.ts

After importing `adm-zip` with the TypeScript style, when compiling the
extension I'd get the error
```
src/server/messages.ts:31:67 - error TS2345: Argument of type 'Buffer' is not assignable to parameter of type 'string'.
31     const fullMessage = createMultipart("atf", filename, project, encodedText,
~~~~~~~~~~~
Found 1 error.
```

Make `encodedText` a string in `validate` function

---

package-lock.json
package.json
src/extension.ts
src/logger.ts
src/test/suite/extension.test.ts
src/test/suite/logger.test.ts

I looked into adding a test to check that the commands are there, but it looks
tricky.  In particular, I tried [`getCommands`](https://code.visualstudio.com/api/references/vscode-api#commands.executeCommand),
as suggested by Anastasis, but I hard some hard time getting something
useful from there.  Unless someone else wants to spend more time on this, I'd
suggest to just merge this without more tests.

Add `adm-zip` and `xml2js` back to dependencies

---

src/server/messages.ts

Fixes #50. This should no longer produce a 400 error when submitting the validation request (the code will fail later on our side when waiting for the final response but that is due to a known problem).
It would be good to have a regression test for this (i.e. that the message we create for the initial request contains the attachment). Any ideas?

Include zip in validation request

---

src/client/server_result.ts
src/extension.ts
src/logger.ts
src/server/messages.ts
src/test/suite/reference/user_log_error.log
src/test/suite/validation.test.ts
src/view.ts

Addresses #29. Have commented out the communication with the server temporarily so we can use the mock result.
This
- shows a popup with the overall result of the validation
- logs the server response (to console and file)
- underlines the lines with errors

Display validation results

---

webpack.config.js

Note that `stats.warningsFilter` is deprecated in favor of `ignoreWarnings`.
Fix #65, close #63.

Let webpack ignore a warning about missing `original-fs` in `adm-zip`

---

package-lock.json
package.json

Before:
```console
% npm audit 
nanoid  <3.1.31
Severity: moderate
Exposure of Sensitive Information to an Unauthorized Actor in nanoid - https://github.com/advisories/GHSA-qrpm-p2h7-hrv2
fix available via `npm audit fix`
node_modules/nanoid
mocha  8.2.0 - 9.1.4
Depends on vulnerable versions of nanoid
node_modules/mocha
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
fix available via `npm audit fix`
node_modules/node-fetch
3 vulnerabilities (2 moderate, 1 high)
To address all issues, run:
npm audit fix
```
After:
```console
% npm audit     
found 0 vulnerabilities
```
Close #92.

Update `package-lock.json` to fix security vulnerability

---

package.json

ATF is a mostly plain text file format, it's reasonable to have word wrapping
enabled by default.  This is also what the Markdown extension does.
Fix #93.

Enable by default word wrapping

---

src/extension.ts

Fix #99 by enforcing the `.atf` extension in the filename when submitting it to the server.  Happy to reword the error message if it isn't clear or it sounds odd.
Preview:

Enforce `.atf` extension when submitting tasks to the server

---

src/extension.ts

I was going to add more commands here and stumbled again on these disposable
variables, which I never liked (but I'm also the person to blame for adding
them), and the odd names came up already in previous reviews:
https://github.com/oracc/nisaba/pull/72#discussion_r714308121.
This should be a non-functional change.
The diff is easier to read if excluding whitespace changes.

Dispose disposable variables

---

src/test/suite/extension.test.ts

At the moment we are only testing that all commands listed in `package.json` are registered in the extension, but not the other way around, that is that all registered commands are listed in `package.json`.

Test that all commands registed in the extension are in `package.json`

---

src/test/suite/input/arabic_no_lem.atf
src/test/suite/input/english_broken.atf
src/test/suite/input/english_no_lem.atf
src/test/suite/lemmatisation.test.ts
src/test/suite/reference/arabic_with_lem.atf
src/test/suite/reference/english_with_lem.atf

I basically replicated [the tests in Nammu](https://github.com/oracc/nammu/blob/9c7179545ea3355a2fe10c1166e079fbe6b9fd47/python/nammu/test/test_nammu.py#L164-L193).  Could maybe add more?
When this is ready, it should close #4.

Add tests for lemmatisation

---

.github/workflows/tag.yml

See https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/.

Update for deprecated GitHub Actions syntax

---

.github/workflows/ci.yml

Node.js 12 is deprecated in GitHub Action runners ([source](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)). This shouldn't affect much or anything.

Update Node.js version in CI

---

src/atf_model.ts
src/client/SOAP_client.ts
src/extension.ts

While debugging #129 (which I still can't reproduce locally, the provided file works for me on Linux :cry:) I noticed that interactions with the server could do it with a bit more of debug messages (like the name of the project found), or a bit clearer (prefix `names` and `contents` with what they are) or actually printing something useful (`fullMessage.toString()` is just `[object Object]`).

Log more debug messages during interaction with server

---

src/oracc_cmd.ts

After playing more with this I realised that showing to the user these messages
in the console may be more useful than hiding them in the log file.

Turn debug log messages around `oracc` command into info messages

---

src/client/server_result.ts

At the end of the lemmatisation process we were printing "ATF validation returned no errors", which was a bit confusing.

In log message refer to ATF lemmatisation with the correct name

---

package.json

It was accidentally removed because apparently the `when` clause does not
support parentheses.

Restore "About Nisaba" button

---

CHANGELOG.md
package-lock.json
package.json

Release v1.4.0 was rejected because of a problem in the README file, but we
can't replace it because it exists anyway in Azure, so we have to do a brand-new
release even if v1.4.0 doesn't appear anywhere visible to users.

Release v1.4.1

---

src/client/SOAP_client.ts

This resolves a deprecation warning in new `node-fetch`.
***Edit***: aargh, this needs more work.

Change `response.buffer` -> `response.arrayBuffer`
